version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: accounting-db
    restart: always
    environment:
      POSTGRES_DB: accounting_system
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 10s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
